---
mgmt_gateway: 192.168.0.1
mgmt_interface: Management0

name_servers:
  - 8.8.8.8

dns_domain: avd.lab

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash(salt='workshop') }}"

daemon_terminattr:
  cvaddrs:
    - apiserver.cv-staging.corp.arista.io:443
  cvauth:
    method: token-secure
    token_file: "/mnt/flash/cv-onboarding-token"
  cvvrf: MGMT
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  disable_aaa: True
